# Generated by Django 2.2.1 on 2019-08-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='bust',
            field=models.FloatField(blank=True, null=True, verbose_name='Busto(cm)'),
        ),
        migrations.AddField(
            model_name='client',
            name='butt',
            field=models.FloatField(blank=True, null=True, verbose_name='Bunda(cm)'),
        ),
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura(m)'),
        ),
        migrations.AddField(
            model_name='client',
            name='waist',
            field=models.FloatField(blank=True, null=True, verbose_name='Cintura(cm)'),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso(kg)'),
        ),
    ]
