# Generated by Django 2.2.1 on 2019-08-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190805_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceseyecolor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='choiceseyecolor',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='choicesgenre',
            name='created',
        ),
        migrations.RemoveField(
            model_name='choicesgenre',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='modified',
        ),
    ]
