# Generated by Django 2.2.4 on 2019-08-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
