# Generated by Django 2.2.4 on 2019-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_client_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Em evidencia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Pequena descrição'),
        ),
    ]
