# Generated by Django 2.2.4 on 2019-08-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_auto_20190810_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name'], 'verbose_name': '$Cliente', 'verbose_name_plural': '$Clientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Evidencia'),
        ),
    ]
