# Generated by Django 2.2.4 on 2019-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_auto_20190810_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Apelido'),
        ),
    ]
