# Generated by Django 2.2.4 on 2019-08-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_auto_20190810_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-modified'], 'verbose_name': '$Cliente', 'verbose_name_plural': '$Clientes'},
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Apelido'),
        ),
    ]
